AppBlog/urls.py
from django.urls import path
from AppBlog import views
urlpatterns = [

path('',views.PostView,name='post-view'),
path('detailviewpub/<int:slug>/',views.post_detail,name='detail-view'),
path('categoryview/<str:cat_id>/',views.CategoryView,name='category'),
path('contactme/',views.Contact_view,name='contact-view'),
path('CoursView/',views.CoursView,name="cours-view"),
path('searchdata/',views.Search_view,name='search-view'),
path('userinformation/',views.Userinformation_View,name='userinformation-view'),
path('UpdateProfile/',views.updateProfile,name='update-view'),
path('UpdateProfilePic/',views.UploadImage_view,name='upload-view'),
path('AdminDeletePost/<int:pk>/',views.Deleteview.as_view(),name='admindeletepost-view'),
path('deletepage/<int:pk>/',views.Delete,name='deletepage-view'),
path('passwordupdate/',views.change_password,name='passwordupdate-view')


]

MONBLOG/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('AppBlog.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

AppBlog/models.py
from django.db import models
from django_quill.fields import QuillField

# Create your models here.

class Email(models.Model):
    email=models.EmailField(max_length=100,null=False,blank=False)
    subject=models.CharField(max_length=100,null=False,blank=False)
    datatime=models.DateTimeField(auto_now_add=True)
    document=models.FileField(null=True,blank=True,upload_to='Email_documents/')
    message=models.TextField(max_length=10000,null=False,blank=False)
    class Meta:
        db_table='Email'
        ordering=('-datatime',)


    def __str__(self):
        return self.subject+" "+self.message

class Cours(models.Model):
    choix=(
         ('', ''),
        ('python', 'python'),
        ('javascript', 'javascript'),
        ('django', 'django'),
        ('css3', 'css3'),
        ('html', 'html'),
        ('java', 'java'),
        
    )
    matier=models.CharField(max_length=300, choices=choix,blank=True,null=True,help_text='selection la matier svp')
    pdf_cours = models.FileField(help_text='selectionner le cours concerner',upload_to='cours/',null=False,blank=False)
    datetime=models.DateTimeField(auto_now=True)
    name=models.CharField(help_text='Non du document cest tres important pour les eleves',max_length=400,default='cours python')

    class Meta:
        db_table="cours"
        ordering=('-datetime',)
    def __str__(self):
        return self.name+" "+self.matier+" "+str(self.datetime)



class Post(models.Model):
    choix=(
		 ('', ''),
        ('python', 'python'),
        ('javascript', 'javascript'),
        ('django', 'django'),
        ('css3', 'css3'),
        ('html', 'html'),
        ('java', 'java'),
        ('annonce', 'annonce'),
        ('autres', 'autres')
    )
    categorie=models.CharField(max_length=300, choices=choix,blank=True,null=True)
    body=QuillField()
    image = models.ImageField(help_text='image',upload_to='images',null=True,blank=True)
    document_pdf = models.FileField(help_text='pdf',upload_to='document_pdf/',null=True,blank=True)
    datetime=models.DateTimeField(auto_now=True)
    document_video=models.FileField(help_text='video',upload_to='document_video/',null=True,blank=True)
	


    class Meta:
        db_table='Post'
        ordering = ('-datetime',)
    def __str__(self):
        return self.categorie+" "+str(self.datetime)



class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80,null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    photo=models.ImageField(upload_to='commentprofile',null=True,blank=True)
    content=QuillField()
    created_on = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.content, self.name)

AppBlog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.contrib import messages
from AppBlog.models import Post,Cours
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .form import CommentForm,CommentForm1,PostForm
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.utils.html import strip_tags
from django.core.mail import EmailMessage
from accounts.models import Profile
from .models import Comment
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView,DeleteView
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm


def change_password(request):
	data=Profile.objects.get(user=request.user)
	information=User.objects.get(username=request.user)
	if request.method == 'POST':
		form = PasswordChangeForm(request.user, request.POST)
		if form.is_valid():
			user = form.save()
			update_session_auth_hash(request, user)  # Important!
			messages.success(request, 'Your password was successfully updated!')
			return redirect('userinformation-view')
		else:
			messages.error(request, 'Please correct the error below.')
	else:
		form = PasswordChangeForm()
	return render(request, 'appblog/userinformation.html',{'form': form,'data':data,'information':information})




class Adminpostpage_view(UpdateView):
	model=Post
	fields='__all__'
	template_name='appblog/adminupdatepost.html'
	success_url='/'



class Deleteview(DeleteView):
	model=Post
	template_name='appblog/areyousure.html'
	success_url='/'
	



def Delete(request,pk):
	return redirect('admindeletepost-view',pk=pk)


@login_required(login_url='login-view')
def UploadImage_view(request):
	if request.method=='POST' and request.FILES['photo']:
		photo=request.FILES['photo']
		Profile_pic_update=Profile.objects.get(user=request.user)
		Profile_pic_update.photo=photo
		Profile_pic_update.save()
		messages.success(request,'votre photo de profile est bien mise a jours merci !!!')
		return redirect('userinformation-view')

@login_required(login_url='login-view')
def Userinformation_View(request):
	data=Profile.objects.get(user=request.user)
	information=User.objects.get(username=request.user)

	return render(request,'appblog/userinformation.html',{'data':data,'information':information})

@login_required(login_url='login-view')
def updateProfile(request):

	if request.method=='POST':

		username=request.POST['username']
		last_name=request.POST['last_name']
		first_name=request.POST['first_name']
		telephone=request.POST['telephone']
		email=request.POST['email']

		# creation dun nouvelle instance de user_cible
		user_cible=User.objects.get(username=request.user)


		user_cible.username=username
		user_cible.email=email
		user_cible.last_name=last_name
		user_cible.first_name=first_name
		user_cible.save()


       # creation dun nouvelle instance de user_cible

		profile_user_cible=Profile.objects.get(user=request.user)
		profile_user_cible.telephone=telephone
		profile_user_cible.save()
		messages.success(request,'votre profile est bien mise a jours merci !!!')



		return redirect('userinformation-view')

@login_required(login_url='login-view')
		
def Search_view(request):
	categorie1=Post.objects.filter(categorie="python")
	categorie2=Post.objects.filter(categorie="java")
	categorie3=Post.objects.filter(categorie="django")
	categorie4=Post.objects.filter(categorie="javascript")
	categorie5=Post.objects.filter(categorie="css3")
	categorie6=Post.objects.filter(categorie="c")
	categorie7=Post.objects.filter(categorie="html")
	categorie8=Post.objects.filter(categorie="bootstrap")
	categorie9=Post.objects.filter(categorie="autres")
	post=Post.objects.all()
	if request.method=='GET':
		search_result=request.GET.get('searchdata')
		if search_result:
			resultas=Post.objects.filter(categorie=search_result)
			
			return render(request,'appblog/search.html',{'search_result':search_result,'resultas':resultas,'post':post,'categorie8':categorie8,'categorie9':categorie9,'categorie1':categorie1,'categorie2':categorie2,'categorie3':categorie3,'categorie4':categorie4,'categorie5':categorie5,'categorie6':categorie6,'categorie7':categorie7})
		else:
			return render(request,'appblog/search.html',{'post':post,'categorie8':categorie8,'categorie9':categorie9,'categorie1':categorie1,'categorie2':categorie2,'categorie3':categorie3,'categorie4':categorie4,'categorie5':categorie5,'categorie6':categorie6,'categorie7':categorie7})
	else:
		return render(request,'appblog/search.html',{'search_result':search_result,'post':post,'categorie8':categorie8,'categorie9':categorie9,'categorie1':categorie1,'categorie2':categorie2,'categorie3':categorie3,'categorie4':categorie4,'categorie5':categorie5,'categorie6':categorie6,'categorie7':categorie7})





@login_required(login_url='login-view')

def CoursView(request):

	categorie1=Cours.objects.filter(matier="python")
	categorie2=Cours.objects.filter(matier="java")
	categorie3=Cours.objects.filter(matier="django")
	categorie4=Cours.objects.filter(matier="javascript")
	categorie5=Cours.objects.filter(matier="css3")
	categorie6=Cours.objects.filter(matier="c")
	categorie7=Cours.objects.filter(matier="html")
	categorie8=Cours.objects.filter(matier="bootstrap")
	doc=Cours.objects.all()
	

	context={'doc':doc,'categorie8':categorie8 ,'categorie1':categorie1,'categorie2':categorie2,'categorie3':categorie3,'categorie4':categorie4,'categorie5':categorie5,'categorie6':categorie6,'categorie7':categorie7}
	return render(request,'appblog/cours.html',context)






def Contact_view(request):
	categorie1=Post.objects.filter(categorie="python")
	categorie2=Post.objects.filter(categorie="java")
	categorie3=Post.objects.filter(categorie="django")
	categorie4=Post.objects.filter(categorie="javascript")
	categorie5=Post.objects.filter(categorie="css3")
	categorie6=Post.objects.filter(categorie="c")
	categorie7=Post.objects.filter(categorie="html")
	categorie8=Post.objects.filter(categorie="bootstrap")
	categorie9=Post.objects.filter(categorie="autres")
	post=Post.objects.all()
	if request.method == 'GET':
		form = CommentForm1()
	else:
		form = CommentForm1(request.POST,request.FILES)
		if form.is_valid():
			subject =request.POST.get('subject')
			email =request.POST.get('email')
			message = request.POST.get('message')
			email = EmailMessage(
			subject,
			message+"\n\n\n\n\n\n\n "+"Emetteur:"+" "+email,
			email,
			['massalylamine22@gmail.com'],
			headers={'Reply-To': email})
			if request.FILES:
				uploaded_file = request.FILES['document']
				email.attach(uploaded_file.name, uploaded_file.read(), uploaded_file.content_type)
			form.save()
			messages.success(request,"votre message est bien envoyer a l'administrateur du site vous recevrais une reponse en moins de 24 heurs !!!!")
			email.send()
			return redirect('/')
	return render(request, "appblog/contact.html", {'form': form,'categorie8':categorie8 ,'categorie1':categorie1,'categorie2':categorie2,'categorie3':categorie3,'categorie4':categorie4,'categorie5':categorie5,'categorie6':categorie6,'categorie7':categorie7})



def PostView(request):
	categorie1=Post.objects.filter(categorie="python")
	categorie2=Post.objects.filter(categorie="java")
	categorie3=Post.objects.filter(categorie="django")
	categorie4=Post.objects.filter(categorie="javascript")
	categorie5=Post.objects.filter(categorie="css3")
	categorie6=Post.objects.filter(categorie="c")
	categorie7=Post.objects.filter(categorie="html")
	categorie8=Post.objects.filter(categorie="annonces")
	categorie9=Post.objects.filter(categorie="autres")
	post = Post.objects.all()
	paginator = Paginator(post, 3) # Show 3 contacts per page.
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)

	return render(request, 'appblog/index.html',{'post':post,'page_obj': page_obj,'categorie8':categorie8,'categorie9':categorie9,'categorie1':categorie1,'categorie2':categorie2,'categorie3':categorie3,'categorie4':categorie4,'categorie5':categorie5,'categorie6':categorie6,'categorie7':categorie7})


@login_required(login_url='login-view')
def post_detail(request, slug):
	categorie1=Post.objects.filter(categorie="python")
	categorie2=Post.objects.filter(categorie="java")
	categorie3=Post.objects.filter(categorie="django")
	categorie4=Post.objects.filter(categorie="javascript")
	categorie5=Post.objects.filter(categorie="css3")
	categorie6=Post.objects.filter(categorie="c")
	categorie7=Post.objects.filter(categorie="html")
	categorie8=Post.objects.filter(categorie="annonces")
	categorie9=Post.objects.filter(categorie="autres")
	post_data = Post.objects.all()
	# profile
	profile_pic=Profile.objects.get(user=request.user)
	# affciher le bouton sup si log== admin
	if request.user.username=='admin':
		delete_post=True
	else:
		delete_post=False

	template_name ="appblog/detail.html"
	post = get_object_or_404(Post, pk=slug)
	comments = post.comments.all()
	new_comment=None
	if request.method == 'POST':

		comment_form = CommentForm(request.POST)
		if comment_form.is_valid():

			new_comment = comment_form.save(commit=False) 
			new_comment.post = post
			new_comment.photo=profile_pic.photo
			new_comment.email=request.user.email
			new_comment.name=request.user.first_name +" "+request.user.last_name
			new_comment.save()
			messages.success(request,"votre commentaire est bien enregsitrer merci")	
			return redirect('detail-view',slug=post.pk)	
	
	else:
		comment_form = CommentForm()
	return render(request, template_name, {'delete_post':delete_post,'post': post,'comments': comments,'comment_form': comment_form,'categorie8':categorie8,'categorie9':categorie9,'categorie1':categorie1,'categorie2':categorie2,'categorie3':categorie3,'categorie4':categorie4,'categorie5':categorie5,'categorie6':categorie6,'categorie7':categorie7,'postdata':post_data})






	

AppBlog/templates/appblog/areyousure.html
{% extends './base.html'%}

{% load static %}
{%block content%}

<form method="post">{% csrf_token %}
    <p><strong>Are you sure you want to delete ""?</strong></p>


  <div class="card">
  <div class="card-header">
    Post ID : {{object.pk}} 
  </div>
  <div class="card-body">
    <h5 class="card-title">Date : {{object.datetime}} </h5>
    <p class="card-text">{{ object.body.html|safe }}</p>
    <a href="{% url 'detail-view' object.pk%}" class="btn btn-dark">Go Back</a>
  </div>
</div>
</br>
    <input type="submit" class="btn btn-danger" value="Confirm">
</form>
</br>
{%endblock%}

AppBlog/templates/appblog/calendar.html
{% load static%}

<link rel="stylesheet" href="{%static 'css/styl.css'%}">
<head>

	</head>
	<body>
	
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="calendar calendar-first" id="calendar_first">
				    <div class="calendar_header">
				        <button class="switch-month switch-left"> <i class="fa fa-chevron-left"></i></button>
				         <h2></h2>
				        <button class="switch-month switch-right"> <i class="fa fa-chevron-right"></i></button>
				    </div>
				    <div class="calendar_weekdays"></div>
				    <div class="calendar_content"></div>
					</div>
				</div>
			</div>
		</div>
	

	<script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/popper.js'%}"></script>
  <script src="{% static 'js/main.js'%}"></script>

	</body>
</html>

AppBlog/templates/appblog/detail.html
{% extends './base.html'%}
{%load crispy_forms_tags%}
{%load static%}


{%block content%}
        <!-- Main Content-->


        <style type="text/css">
          
          input[name='name'],input[name='email']{

              display: none;


          }

          label[for='id_email'],label[for='id_name']{


            display: none;
          }

        </style>
  
            <div class="row">
                  <div class="col-md-8">
                      {%if post%}
                    
              

                        <div class="card mb-3">
                          
                                
                                      <div class="card-body">
                                        <h5 class="card-title"><img src="https://media.istockphoto.com/vectors/caucasian-bridegroom-wearing-a-black-suit-in-cartoon-style-vector-vector-id1141905006?k=6&m=1141905006&s=170667a&w=0&h=MeiLI744Ge128M1YFJpq3zBxb4WycxbQ-SSFSx6STP4=" width=30px height=30px/> Categorie : {{post.categorie}}</h5>
                                        <p class="card-text">
                                          <p  class="font-monospace">
                                              {%if post.image %}
                                            
                                                <img src="{{post.image.url}}" style="width: max-content/3; height: max-content/3; border:10px;border-radius: 20px;" class="card-img-top" alt="Wild Landscape"/>

                                                {%endif%}</br></br>

                                             {% if post.document_video%}
                                             <h4 style="font-family:monospace;">Tutoriel en {{post.categorie}}</h4></br></br>

                                            <video width="450" height="340" controls><source src="{{post.document_video.url}}" type="video/mp4">

                                             Votre navigateur ne permet pas de lire les vidéos HTML5.
                                           </video>
                                           {%else%}
                                          {%endif%}</br> </br> 

                                          {{post.body.html|safe}}</br> {%if post.document_pdf%}
                                          <span style="font-family:monospace;  color: red; font-size: 20px;"ss>Telecharger: &nbsp;</span>  
                                          <a href="{{post.document_pdf.url}}" style="color:blue" download="Acme Documentation (ver. 2.0.1).txt">{{post.document_pdf}}</a>{%endif%}</br></</br>

                                          {%if delete_post%}

                                             <form action="{% url 'deletepage-view' post.id%}" method="post">
                                              {% csrf_token %}
                                                <button class="btn btn-danger" type="submit">Delete Post</button>

                                             </form></br>

                                            
                                          {%else%}
                                          {%endif%}
                                         

                                          </p>
                                        
                                        </p>
                                        <p class="card-text">
                                          <strong>publier le :  </strong>{{post.datetime}}
                                        </p>
                                      </div>
                                    </div>
                         
                             {%endif%}


                                          <!-- all commentaire-->

                              </hr>
                              <h3 style="font-family:monospace;" class="bg-primary">commentaires :</h3></br>

                                   {% for comment in comments %}
                                          <div class="bg-light bg-gradient" style="padding: 10px;">
                                            <p class="font-weight-bold">
                                              <img src="{{comment.photo.url}}"  width="60px" height="60px" style="border:5px; border-radius: 10px;" /> {{ comment.name }}
                                              <span class=" text-muted font-weight-normal">
                                                {{ comment.created_on }}
                                              </span> </p>
                                         
                                              <a href="mailto:{{comment.email}}">email : {{comment.email}}</a>
                                           
                                            {{ comment.content.html|safe| linebreaks }}
                                          </div>
                                        </hr>
                                          {% endfor %}


                        <!-- end commentaire-->

                           <!-- comment  form block-->

                
                            <div class="card-body">
                              {%if messages%}
                            {%for messages in messages%}
                              <div class="alert alert-success" role="alert">
                                {{messages}}
                                
                              </div>
                              {%endfor%}
                              {%endif%}

                              <h3 style="font-family: monospace; float:right;" class="bg-success">Commentez-ici</h3>
                              <form method="post" style="margin-top: 1.3em;">
                                {% csrf_token %}
                                {{comment_form.media}}
                                {{comment_form|crispy}}

                                <button type="submit" class="btn btn-primary  btn-lg"  id="comentaire">Submit</button>
                              </form>
                              
                            </div>


                           <!--end block comment fomr-->


                    
                    </div>

                  <div class="col-md-4">



                                        <!--- boite de navigation-->
                            <div class="list-group">
                            <button type="button" class="list-group-item list-group-item-action active" aria-current="true">
                              Tableau Bord
                            </button>
                              <ol class="list-group list-group-numbered">
                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                  <div class="ms-2 me-auto">
                                    <div class="fw-bold"><a href="{%url 'category' 'python' %}" >Programmation en PYTHON 3</a></div>
                                    version 3
                                  </div>
                                  <span class="badge bg-primary rounded-pill">{{categorie1|length}}</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                  <div class="ms-2 me-auto">
                                    <div class="fw-bold"><a href="{%url 'category' 'java' %}">Programmation en JAVA</a></div>
                                    tous les versions
                                  </div>
                                  <span class="badge bg-primary rounded-pill">{{categorie2|length}}</span>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                  <div class="ms-2 me-auto">
                                    <div class="fw-bold"><a href="{%url 'category' 'django' %}">Programmation en DJANGO</a></div>
                                    version 3 , 4.0 et 4.1
                                  </div>
                                  <span class="badge bg-primary rounded-pill">{{categorie3|length}}</span>

                                </li>
                                  <li class="list-group-item d-flex justify-content-between align-items-start">
                                  <div class="ms-2 me-auto">
                                    <div class="fw-bold"><a href="{%url 'category' 'javascript' %}">Programmation en JAVASCRIP ET JQUERY</a></div>
                                    tous les versions
                                  </div>
                                  <span class="badge bg-primary rounded-pill">{{categorie4|length}}</span>
                                </li>

                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                  <div class="ms-2 me-auto">
                                    <div class="fw-bold"><a href="{%url 'category' 'css3' %}">Programmation en CSS3 ET BOOTSTRAP</a></div>
                                    tous les versions
                                  </div>
                                  <span class="badge bg-primary rounded-pill">{{categorie5|length}}</span>
                                </li>

                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                  <div class="ms-2 me-auto">
                                    <div class="fw-bold"><a href="{%url 'category' 'c' %}">Programmation en C </a></div>
                                    tous les versions
                                  </div>
                                  <span class="badge bg-primary rounded-pill">{{categorie6|length}}</span>
                                </li>

                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                  <div class="ms-2 me-auto">
                                    <div class="fw-bold"><a href="{%url 'category' 'html' %}">Programmation en HTML5</a> </div>
                                    version 5
                                  </div>
                                  <span class="badge bg-primary rounded-pill">{{categorie7|length}}</span>
                                </li>

                                <li class="list-group-item d-flex justify-content-between align-items-start">
                                      <div class="ms-2 me-auto">
                                        <div class="fw-bold"><a href="{%url 'category' 'annonces' %}">Annonces</a> </div>
                                        
                                      </div>
                                      <span class="badge bg-primary rounded-pill">{{categorie8|length}}</span>
                                    </li>
                                       
                                        <li class="list-group-item d-flex justify-content-between align-items-start">
                                      <div class="ms-2 me-auto">
                                        <div class="fw-bold"><a href="{%url 'category' 'autres' %}">Autres</a> </div>
                                      
                                      </div>
                                      <span class="badge bg-primary rounded-pill">{{categorie9|length}}</span>
                                    </li>


                              </ol>
                            </div>

                                  </br></br>

                              <div class="card text-white bg-primary mb-6" style="max-width: 35rem;">
                              <div class="card-header">Total De Publication</div>
                              <div class="card-body">
                                <h5 class="card-title"></h5>
                                <p class="card-text"> {{postdata|length}} Publication Au Total</p>
                              </div>


                          </div>

            <!-- fin boite de navigation-->
                         {%include './calendar.html'%}

                      
                  </div>


            </div>
            <script type="text/javascript">
              


            $(document).ready(function () {
             
               $("#comentaire").click(function(){

                           //var $email=$("input[name='email']").val()
                           //var $name=$("input[name='name']").val()
                           var $content=$("input[name='content']").val()
                         
                           if ($content.length===0) {

                             swal("Message Du Serveur!!!", " Message : Tous Les Champs Sont Aubligatoires !!!");
                           }



                            
               });
});

            </script>

           
    

        <!-- Footer-->

        {%endblock content%}